from __future__ import annotations

import re


def normalize_reference_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def mapping(tissue: str, role: str, loading_factor: float) -> dict[str, object]:
    return {
        "tissue": tissue,
        "role": role,
        "loading_factor": loading_factor,
    }


TISSUE_RECOVERY_HOURS_FIXUPS: dict[str, float] = {
    "rectus_abdominis": 36.0,
    "transverse_abdominis": 36.0,
    "external_oblique": 36.0,
    "internal_oblique": 36.0,
    "diaphragm": 36.0,
    "pelvic_floor": 36.0,
    "biceps_long_head_tendon": 96.0,
    "supraspinatus_tendon": 96.0,
    "common_extensor_tendon": 96.0,
    "common_flexor_tendon": 96.0,
    "patellar_tendon": 96.0,
    "hamstring_tendons": 96.0,
    "achilles_tendon": 96.0,
    "wrist_joint": 60.0,
    "shoulder_joint": 84.0,
    "lumbar_spine": 84.0,
}


# Keep cable woodchoppers out of the generic correction set because the user's
# version intentionally loads grip/forearms much harder than a typical chop.
REFERENCE_EXERCISE_FIXUPS: dict[str, dict[str, object]] = {
    "Assisted Pull-Ups": {
        "load_input_mode": "assisted_bodyweight",
        "bodyweight_fraction": 1.0,
    },
    "Wide Pull-ups (Assist)": {
        "load_input_mode": "assisted_bodyweight",
        "bodyweight_fraction": 1.0,
    },
    "Push-ups": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.64,
        "estimated_minutes_per_set": 1.5,
    },
    "Incline Push-Up": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.45,
        "estimated_minutes_per_set": 1.5,
    },
    "Dips": {
        "load_input_mode": "mixed",
        "bodyweight_fraction": 0.95,
        "estimated_minutes_per_set": 1.5,
    },
    "Weighted Plank": {
        "load_input_mode": "mixed",
        "bodyweight_fraction": 0.6,
        "estimated_minutes_per_set": 1.25,
        "mappings": [
            mapping("transverse_abdominis", "primary", 0.9),
            mapping("rectus_abdominis", "secondary", 0.65),
            mapping("external_oblique", "secondary", 0.55),
            mapping("internal_oblique", "secondary", 0.55),
            mapping("serratus_anterior", "secondary", 0.45),
            mapping("diaphragm", "stabilizer", 0.25),
            mapping("pelvic_floor", "stabilizer", 0.25),
            mapping("gluteus_maximus", "stabilizer", 0.25),
            mapping("shoulder_joint", "stabilizer", 0.35),
            mapping("wrist_joint", "stabilizer", 0.25),
            mapping("elbow_joint", "stabilizer", 0.15),
            mapping("hip_joint", "stabilizer", 0.15),
        ],
    },
    "Hanging Leg Raises": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.45,
        "estimated_minutes_per_set": 1.5,
        "mappings": [
            mapping("rectus_abdominis", "primary", 0.8),
            mapping("iliacus", "primary", 0.75),
            mapping("psoas_major", "primary", 0.75),
            mapping("transverse_abdominis", "secondary", 0.35),
            mapping("external_oblique", "secondary", 0.3),
            mapping("internal_oblique", "secondary", 0.3),
            mapping("latissimus_dorsi", "stabilizer", 0.25),
            mapping("flexor_digitorum_superficialis", "stabilizer", 0.25),
            mapping("flexor_digitorum_profundus", "stabilizer", 0.25),
            mapping("brachioradialis", "stabilizer", 0.2),
            mapping("shoulder_joint", "stabilizer", 0.3),
            mapping("wrist_joint", "stabilizer", 0.2),
            mapping("elbow_joint", "stabilizer", 0.15),
        ],
    },
    "Flutter Kicks": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.2,
        "estimated_minutes_per_set": 1.25,
    },
    "Laying Down Crunches": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.18,
        "estimated_minutes_per_set": 1.0,
    },
    "Reverse Crunch + isometric crunch": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.25,
        "estimated_minutes_per_set": 1.0,
    },
    "Dead Bug": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.12,
        "estimated_minutes_per_set": 1.0,
    },
    "Box Jumps": {
        "load_input_mode": "bodyweight",
        "bodyweight_fraction": 0.65,
        "estimated_minutes_per_set": 1.0,
    },
    "Bulgarian Split Squat": {
        "load_input_mode": "mixed",
        "bodyweight_fraction": 0.75,
        "mappings": [
            mapping("gluteus_maximus", "primary", 0.75),
            mapping("rectus_femoris", "primary", 0.65),
            mapping("vastus_lateralis", "primary", 0.65),
            mapping("vastus_medialis", "primary", 0.65),
            mapping("vastus_intermedius", "secondary", 0.5),
            mapping("gluteus_medius", "secondary", 0.4),
            mapping("adductor_magnus", "secondary", 0.35),
            mapping("semimembranosus", "secondary", 0.2),
            mapping("semitendinosus", "secondary", 0.2),
            mapping("biceps_femoris_long_head", "secondary", 0.2),
            mapping("hip_joint", "stabilizer", 0.3),
            mapping("knee_joint", "stabilizer", 0.35),
            mapping("patellar_tendon", "stabilizer", 0.35),
            mapping("ankle_joint", "stabilizer", 0.2),
            mapping("achilles_tendon", "stabilizer", 0.2),
            mapping("gluteus_minimus", "stabilizer", 0.2),
            mapping("pelvic_floor", "stabilizer", 0.15),
        ],
    },
    "Walking Lunges": {
        "load_input_mode": "mixed",
        "bodyweight_fraction": 0.7,
        "mappings": [
            mapping("gluteus_maximus", "primary", 0.7),
            mapping("rectus_femoris", "primary", 0.6),
            mapping("vastus_lateralis", "primary", 0.6),
            mapping("vastus_medialis", "primary", 0.6),
            mapping("vastus_intermedius", "secondary", 0.45),
            mapping("gluteus_medius", "secondary", 0.35),
            mapping("adductor_magnus", "secondary", 0.3),
            mapping("semimembranosus", "secondary", 0.2),
            mapping("semitendinosus", "secondary", 0.2),
            mapping("hip_joint", "stabilizer", 0.3),
            mapping("knee_joint", "stabilizer", 0.35),
            mapping("patellar_tendon", "stabilizer", 0.35),
            mapping("ankle_joint", "stabilizer", 0.2),
            mapping("achilles_tendon", "stabilizer", 0.2),
            mapping("gluteus_minimus", "stabilizer", 0.2),
        ],
    },
    "Farmers Carry": {
        "load_input_mode": "carry",
        "external_load_multiplier": 2.0,
        "estimated_minutes_per_set": 1.0,
        "mappings": [
            mapping("flexor_digitorum_superficialis", "primary", 0.85),
            mapping("flexor_digitorum_profundus", "primary", 0.85),
            mapping("common_flexor_tendon", "secondary", 0.45),
            mapping("upper_trapezius", "secondary", 0.45),
            mapping("wrist_extensors", "secondary", 0.35),
            mapping("brachioradialis", "secondary", 0.35),
            mapping("common_extensor_tendon", "secondary", 0.25),
            mapping("levator_scapulae", "secondary", 0.25),
            mapping("transverse_abdominis", "stabilizer", 0.35),
            mapping("quadratus_lumborum", "stabilizer", 0.3),
            mapping("external_oblique", "stabilizer", 0.3),
            mapping("internal_oblique", "stabilizer", 0.3),
            mapping("lumbar_spine", "stabilizer", 0.35),
            mapping("thoracic_spine", "stabilizer", 0.25),
            mapping("gluteus_medius", "stabilizer", 0.25),
            mapping("shoulder_joint", "stabilizer", 0.25),
            mapping("wrist_joint", "stabilizer", 0.25),
            mapping("hip_joint", "stabilizer", 0.2),
            mapping("gluteus_minimus", "stabilizer", 0.2),
            mapping("cervical_spine", "stabilizer", 0.15),
        ],
    },
    "Barbell Curl": {
        "mappings": [
            mapping("biceps_long_head", "primary", 0.72),
            mapping("biceps_short_head", "primary", 0.72),
            mapping("brachialis", "secondary", 0.55),
            mapping("brachioradialis", "secondary", 0.3),
            mapping("biceps_long_head_tendon", "secondary", 0.2),
            mapping("elbow_joint", "stabilizer", 0.2),
            mapping("wrist_joint", "stabilizer", 0.15),
            mapping("shoulder_joint", "stabilizer", 0.1),
        ],
    },
    "Straight-Bar Cable Curl": {
        "mappings": [
            mapping("biceps_long_head", "primary", 0.7),
            mapping("biceps_short_head", "primary", 0.7),
            mapping("brachialis", "secondary", 0.55),
            mapping("brachioradialis", "secondary", 0.3),
            mapping("biceps_long_head_tendon", "secondary", 0.2),
            mapping("common_flexor_tendon", "secondary", 0.2),
            mapping("flexor_digitorum_superficialis", "stabilizer", 0.15),
            mapping("flexor_digitorum_profundus", "stabilizer", 0.15),
            mapping("supinator", "stabilizer", 0.1),
            mapping("pronator_teres", "stabilizer", 0.1),
            mapping("elbow_joint", "stabilizer", 0.2),
            mapping("wrist_joint", "stabilizer", 0.15),
            mapping("shoulder_joint", "stabilizer", 0.1),
        ],
    },
    "Hammer Curl": {
        "mappings": [
            mapping("brachioradialis", "primary", 0.85),
            mapping("brachialis", "primary", 0.75),
            mapping("biceps_long_head", "secondary", 0.35),
            mapping("biceps_short_head", "secondary", 0.35),
            mapping("biceps_long_head_tendon", "secondary", 0.25),
            mapping("pronator_teres", "stabilizer", 0.15),
            mapping("supinator", "stabilizer", 0.15),
            mapping("elbow_joint", "stabilizer", 0.2),
            mapping("wrist_joint", "stabilizer", 0.15),
        ],
    },
    "Preacher Curl": {
        "mappings": [
            mapping("biceps_short_head", "primary", 0.8),
            mapping("brachialis", "secondary", 0.6),
            mapping("biceps_long_head", "secondary", 0.45),
            mapping("brachioradialis", "secondary", 0.2),
            mapping("biceps_long_head_tendon", "secondary", 0.25),
            mapping("elbow_joint", "stabilizer", 0.25),
            mapping("wrist_joint", "stabilizer", 0.15),
        ],
    },
    "Single-Arm Cable Curl": {
        "mappings": [
            mapping("biceps_long_head", "primary", 0.7),
            mapping("biceps_short_head", "primary", 0.7),
            mapping("brachialis", "secondary", 0.55),
            mapping("brachioradialis", "secondary", 0.35),
            mapping("biceps_long_head_tendon", "secondary", 0.2),
            mapping("common_flexor_tendon", "secondary", 0.15),
            mapping("elbow_joint", "stabilizer", 0.2),
            mapping("wrist_joint", "stabilizer", 0.15),
            mapping("shoulder_joint", "stabilizer", 0.05),
        ],
    },
    "Triceps Rope Pushdown": {
        "mappings": [
            mapping("triceps_lateral_head", "primary", 0.8),
            mapping("triceps_medial_head", "primary", 0.75),
            mapping("triceps_long_head", "secondary", 0.45),
            mapping("elbow_joint", "stabilizer", 0.25),
            mapping("wrist_joint", "stabilizer", 0.1),
            mapping("shoulder_joint", "stabilizer", 0.05),
        ],
    },
    "Seated Cable Row": {
        "mappings": [
            mapping("latissimus_dorsi", "primary", 0.9),
            mapping("teres_major", "secondary", 0.45),
            mapping("mid_trapezius", "secondary", 0.55),
            mapping("rhomboid_major", "secondary", 0.5),
            mapping("rhomboid_minor", "secondary", 0.4),
            mapping("lower_trapezius", "secondary", 0.35),
            mapping("posterior_deltoid", "secondary", 0.35),
            mapping("brachialis", "secondary", 0.3),
            mapping("biceps_long_head", "secondary", 0.25),
            mapping("biceps_short_head", "secondary", 0.25),
            mapping("brachioradialis", "secondary", 0.2),
            mapping("shoulder_joint", "stabilizer", 0.25),
            mapping("elbow_joint", "stabilizer", 0.15),
        ],
    },
    "Landmine Row": {
        "mappings": [
            mapping("latissimus_dorsi", "primary", 0.85),
            mapping("teres_major", "secondary", 0.5),
            mapping("mid_trapezius", "secondary", 0.45),
            mapping("rhomboid_major", "secondary", 0.4),
            mapping("rhomboid_minor", "secondary", 0.3),
            mapping("lower_trapezius", "secondary", 0.3),
            mapping("posterior_deltoid", "secondary", 0.35),
            mapping("brachialis", "secondary", 0.25),
            mapping("biceps_long_head", "secondary", 0.2),
            mapping("biceps_short_head", "secondary", 0.2),
            mapping("brachioradialis", "secondary", 0.2),
            mapping("transverse_abdominis", "stabilizer", 0.15),
            mapping("external_oblique", "stabilizer", 0.15),
            mapping("internal_oblique", "stabilizer", 0.15),
            mapping("hip_joint", "stabilizer", 0.15),
            mapping("shoulder_joint", "stabilizer", 0.2),
            mapping("elbow_joint", "stabilizer", 0.15),
        ],
    },
    "Landmine Press": {
        "mappings": [
            mapping("anterior_deltoid", "primary", 0.85),
            mapping("pec_clavicular_head", "primary", 0.65),
            mapping("serratus_anterior", "secondary", 0.45),
            mapping("triceps_long_head", "secondary", 0.4),
            mapping("lateral_deltoid", "secondary", 0.35),
            mapping("pec_sternal_head", "secondary", 0.25),
            mapping("supraspinatus_tendon", "secondary", 0.25),
            mapping("external_oblique", "stabilizer", 0.2),
            mapping("internal_oblique", "stabilizer", 0.2),
            mapping("rectus_abdominis", "stabilizer", 0.15),
            mapping("infraspinatus", "stabilizer", 0.15),
            mapping("subscapularis", "stabilizer", 0.15),
            mapping("supraspinatus", "stabilizer", 0.15),
            mapping("teres_minor", "stabilizer", 0.15),
            mapping("shoulder_joint", "stabilizer", 0.3),
            mapping("elbow_joint", "stabilizer", 0.15),
            mapping("wrist_joint", "stabilizer", 0.1),
        ],
    },
    "Single Leg Extension": {
        "mappings": [
            mapping("vastus_lateralis", "primary", 0.8),
            mapping("vastus_medialis", "primary", 0.8),
            mapping("vastus_intermedius", "primary", 0.75),
            mapping("rectus_femoris", "secondary", 0.4),
            mapping("patellar_tendon", "secondary", 0.65),
            mapping("knee_joint", "stabilizer", 0.4),
            mapping("hip_joint", "stabilizer", 0.05),
        ],
    },
}
